### PR TITLE
Fixed namespace and abstract class issue

### PR DESCRIPTION
**Pull request by Jayanta7022**
https://github.com/dualcube/moodle-tool_inactive_user_cleanup/issues/19

### CODE REVIEW

**Comment by Buda9** [comment]
After updating to your version this is how output in mosta cases looks like:

```
Execute scheduled task: Inactive User Cleanup (tool_inactive_user_cleanup\task\tool_inactive_user_cleanup_task)
... started 11:14:23. Current memory use 3.1 MB.
Hey, admin tool inactive user cleanup is running
tool_inactive_user_cleanup task finished
... used 5087 dbqueries
... used 3.283882856369 seconds
Scheduled task complete: Inactive User Cleanup (tool_inactive_user_cleanup\task\tool_inactive_user_cleanup_task)
```

However, few outputs looked like this:

```
Exception occurred while calling tool_inactive_user_cleanup\privacy\provider::get_contexts_for_userid.
This means that plugin tool_inactive_user_cleanup did not complete the processing of data. The following exception information may be passed on to the plugin developer:

call_user_func_array(): Argument #1 ($callback) must be a valid callback, cannot call abstract method tool_inactive_user_cleanup\privacy\provider::get_contexts_for_userid()


#0 /home/--/web/--/public_html/privacy/classes/manager.php(578): component_class_callback()
#1 /home/--/web/--/public_html/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#2 /home/--/web/--/public_html/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback()
#3 /home/--/web/--/public_html/admin/tool/dataprivacy/classes/task/process_data_request_task.php(93): core_privacy\manager->get_contexts_for_userid()
#4 /home/--/web/--/public_html/lib/classes/cron.php(519): tool_dataprivacy\task\process_data_request_task->execute()
#5 /home/--/web/--/public_html/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task()
#6 /home/--/web/--/public_html/lib/classes/cron.php(128): core\cron::run_adhoc_tasks()
#7 /home/--/web/--/public_html/admin/cron.php(80): core\cron::run_main_process()
#8 {main}
```

Did you encounter this err message during your tests?

**Comment by Buda9** [comment]
Exception occurred while calling tool_inactive_user_cleanup\privacy\provider::get_contexts_for_userid.
This means that plugin tool_inactive_user_cleanup did not complete the processing of data. The following exception information may be passed on to the plugin developer:

call_user_func_array(): Argument #1 ($callback) must be a valid callback, cannot call abstract method tool_inactive_user_cleanup\privacy\provider::get_contexts_for_userid()


#0 /home/-/web/-/public_html/privacy/classes/manager.php(578): component_class_callback()
#1 /home/-/web/-/public_html/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#2 /home/-/web/-/public_html/privacy/classes/manager.php(238): core_privacy\manager->handled_component_class_callback()
#3 /home/-/web/-/public_html/admin/tool/dataprivacy/classes/task/process_data_request_task.php(93): core_privacy\manager->get_contexts_for_userid()
#4 /home/-/web/-/public_html/lib/classes/cron.php(519): tool_dataprivacy\task\process_data_request_task->execute()
#5 /home/-/web/-/public_html/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task()
#6 /home/-/web/-/public_html/lib/classes/cron.php(128): core\cron::run_adhoc_tasks()
#7 /home/-/web/-/public_html/admin/cron.php(80): core\cron::run_main_process()
#8 {main}

**Comment by moumitahalder** [comment]
Hi @Buda9, we are not able to replicate this issue on our end. 

Can you please contact us over [here](https://dualcube.com/contact-us/), so we can debug this issue on your end.

**Comment by moumitahalder** [comment]
@Buda9 and @Snickser , thanks for helping us on this. 
We have fixed them on our end. Can you please test the latest pull?

**Comment by Buda9** [comment]
Looks all good now (Moodle 4.4). Thank you very much for prompt fix.

```
Execute scheduled task: Inactive User Cleanup (tool_inactive_user_cleanup\task\tool_inactive_user_cleanup_task)
... started 16:23:06. Current memory use 3.1 MB.
Hey, admin tool inactive user cleanup is running
USER ID 
2153---xyz@gmail.com
User is inactive for past day 549

...
...

tool_inactive_user_cleanup task finished
... used 5205 dbqueries
... used 15.616523981094 seconds
Scheduled task complete: Inactive User Cleanup (tool_inactive_user_cleanup\task\tool_inactive_user_cleanup_task)
```

**Pull request merged**
